### ISSUE TITLE
FR1: Example Issue

### ISSUE THREAD

**Issue by gza060625** [ECE493W2021T3/eVoter#1]
Newly created Issue will be added to Project:Backlog by system.

But, How to create sub issues? For example FR99 could be splits into several sub tasks. Only finish all sub tasks, this FR99 could be closed. 

One possible solution is: Create sub tasks along with FR99. For example, have issues like:
FR99
Sub-issue1
Sub-issue2
Sub-issue3
.....

Each sub issue closes when the sub task is completed.
But FR99 only closes when no more sub tasks related to FR99.

We could add "FR99" tag to all its sub tasks for tracking.

**Comment by gatilogo** [comment]
Addressed with the addition of FR labels and "Functional Requirements" column
