### ISSUE TITLE
Get/store user setting from/onto Blockchain

### ISSUE THREAD

**Issue by LiyaoJiang1998** [ECE493W2021T3/eVoter#26]
[//]: # (These are comments and are used for reference and will not show up in the issue)

**Description:**

[//]: # (A clear and concise description of what you want to happen.)
Replace any dummy placeholders with Blockchain methods to get and store user setting from/onto Blockchain:
- Create new transaction for storing/update user setting
- Getting user setting from blockchain for edit setting.

**Related Issues or Functional Requirement(s):**

[//]: # (Ex. #<issue id>. Moreover, please add the appropriate FR label.)
#3 #25 

**Related WBS Block Number(s):**

[//]: # (Ex. [1.1], [1.2], etc.)
[2.3]

**Additional context:**

[//]: # (Add any other context or screenshots about the feature request here.)

**Comment by gatilogo** [comment]
User information will no longer be saved to blockchain
