### ISSUE TITLE
UI for poll creation form

### ISSUE THREAD

**Issue by gza060625** [ECE493W2021T3/eVoter#31]
[//]: # (These are comments and are used for reference and will not show up in the issue)

**Description:**

[//]: # (A clear and concise description of what you want to happen.)
Admin click to create a new poll, redirect to Poll creation form.

Form shall have the following fields:
- Type Selection field for Poll Type
- Toggle for Anonymous Mode
- Fields to input multiple choice options
- Fields and Selection List for assigning voters
- Selection field to choose result presentation mode (What/when to show to voters)
- Selection field to choose end date
- Selection filed to choose start date

The form should be validated:
- check if any empty field, show error message for unfilled field
- check correctness and availability(if applicable) of all above fields

**Related Issues or Functional Requirement(s):**

[//]: # (Ex. #<issue id>. Moreover, please add the appropriate FR label.)
#7 

**Related WBS Block Number(s):**

[//]: # (Ex. [1.1], [1.2], etc.)

[6.1] [6.2]*

**Additional context:**

[//]: # (Add any other context or screenshots about the feature request here.)

**Comment by gatilogo** [comment]
> Fields and Selection List for assigning voters
This is addressed in #39
