### ISSUE TITLE
#23 Update User Router

### ISSUE THREAD

**Issue by gza060625** [ECE493W2021T3/eVoter#63]
[//]: # (These are comments and are used for reference and will not show up in the issue)

**Description:**
Update User routing to be compatible with `POST: /users` in #61 

[//]: # (A clear and concise description of what you want to happen.)

**Related Issues or Functional Requirement(s):**
#61 #21

[//]: # (Ex. #<issue id>. Moreover, please add the appropriate FR label.)

**Related WBS Block Number(s):**

[//]: # (Ex. [1.1], [1.2], etc.)

**Additional context:**

[//]: # (Add any other context or screenshots about the feature request here.)

**Comment by gatilogo** [comment]
Closed through #65
